# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rbbcc", path: '../../'
gem "charty", path: '/usr/local/ghq/github.com/udzura/charty'
gem "unicode_plot"
gem "numo"
