#!/usr/bin/env ruby

if ARGV[0] == '-v' || ARGV[0] == '--version'
  require 'rbbcc/version'
  print "RbBCC: version "
  puts RbBCC::VERSION
  print "Using "
  puts RUBY_DESCRIPTION
elsif ARGV[0] == '--invoke'
  require 'rbbcc/invoker'
  ARGV.shift
  RbBCC::Invoker.new(ARGV).run
else
  binpath = File.readlink "/proc/self/exe"
  exec binpath, *ARGV
end
