name: Tests
on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build docker container with all deps
      run: |
        docker build -t rbbcc-ci -f Dockerfile.ci .
    - name: Run test
      run: |
        /bin/bash -c \
                   "docker run --privileged \
                   --pid=host \
                   -v $(pwd):/rbbcc \
                   -v /sys/kernel/debug:/sys/kernel/debug:rw \
                   -v /lib/modules:/lib/modules:ro \
                   -v /usr/src:/usr/src:ro \
                   -v /usr/include/linux:/usr/include/linux:ro \
                   rbbcc-ci \
                   /bin/bash -c \
                   'cd /rbbcc && bundle install && bundle exec rake test'"
    