name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        libbcc_version: [0.29.0, 0.31.0, 0.35.0]
        ruby_version: [4.0.2]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to ghcr.io
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u udzura --password-stdin
    - name: Build docker container with all deps
      run: |
        docker build -t rbbcc-ci-${{ matrix.libbcc_version }}-${{ matrix.ruby_version }} \
                     --build-arg BCC_VERSION=${{ matrix.libbcc_version }} \
                     --build-arg RUBY_VERSION=${{ matrix.ruby_version }} \
                     -f ci/Dockerfile.ci_base ci/
    - name: Run test
      run: |
        /bin/bash -c \
                   "docker run --privileged \
                   --pid=host \
                   -v $(pwd):/rbbcc \
                   -v /sys/kernel/debug:/sys/kernel/debug:rw \
                   -v /lib/modules:/lib/modules:ro \
                   -v /usr/src:/usr/src:ro \
                   -v /usr/include/linux:/usr/include/linux:ro \
                   rbbcc-ci-${{ matrix.libbcc_version }}-${{ matrix.ruby_version }} \
                   /bin/bash -c \
                   'cd /rbbcc && git config --global --add safe.directory /rbbcc && bundle install && bundle exec rake test'"
    
